---
title: Gegevens in kaart brengen
hero_image: images/banner.png
description:
  - Gebruik Python om een interactieve kaart te maken waarmee gebruikers interessante
  - feiten over de wereld kunnen leren
meta_title: Python-coderingsprojecten voor kinderen en tieners | Gegevens in kaart brengen
meta_description: Leer Python met de codeerprojecten van de Raspberry Pi Foundation voor kinderen en tieners. Gebruik Python om een kaart te maken en interessante feiten over de wereld te leren.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: Wat ga je maken
  - 
    title: Kies en laad een dataset
  - 
    title: Kies een kaart en spelden
    completion:
      - engaged
  - 
    title: Je gegevens markeren
    completion:
      - internal
  - 
    title: Snelle quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Verbeter je project
  - 
    title: Delen
  - 
    title: Wat kun je verder nog doen?
